stages:
  # 建立 rancher_pipeline 專用的 Docker Image
  - name: Publish rancher pipeline service image
    steps:
    - publishImageConfig:
        dockerfilePath: ./Dockerfile.pipeline-generate-service
        buildContext: .
        tag: ${CICD_GIT_REPO_NAME}/${CICD_GIT_REPO_NAME}:${CICD_GIT_BRANCH}-${CICD_GIT_COMMIT}
        pushRemote: true
        registry: 10.20.0.73:5443
      env:
        PLUGIN_BUILD_ARGS: --progress=tty --network=host
        PLUGIN_DEBUG: "true"
        PLUGIN_INSECURE: "true"
        PLUGIN_MIRROR: https://10.20.0.73:5443
        PLUGIN_MTU: "1000"

  # 部屬 swagger
  - name: deploy--swagger-editor
    stages:
    - applyYamlConfig:
        path: ./k8s-yaml/swagger-deployment.yaml
    - applyYamlConfig:
        path: ./k8s-yaml/swagger-service.yaml
    - applyYamlConfig:
        path: ./k8s-yaml/swagger-ingress.yaml

  # 部屬restful服務(使用者編寫)
  - name: deploy--restful-service
    stages:
    - applyYamlConfig:
      path: ./k8s-yaml/restful-deployment.yaml
    - applyYamlConfig:
      path: ./k8s-yaml/restful-service.yaml
    - applyYamlConfig:
      path: ./k8s-yaml/restful-ingress.yaml
    
